### ISSUE TITLE
I have Lotus running locally. How do I access?

### ISSUE THREAD

**Issue by stuchalk** [lotusnprod/lotus-web#32]
I want to connect to the local Docker instance of Lotus, so I can run the API query below.  How do I do that?
I have both the mongo and lotus-online containers running, but I only see command line access via the Docker dashboard.

`https://lotus.naturalproducts.net/api/search/simple?query=inchikey`

![Screen Shot 2022-10-14 at 3 11 21 PM](https://user-images.githubusercontent.com/540150/195923212-5506db70-d3ad-4c06-8b1d-31f2a35205d9.jpg)

**Comment by Adafede** [comment]
Hi @stuchalk!

It is difficult to understand what you are looking for following your previous issue.

Maybe you could reach out for more details about your motivations 

Anyway, to be able to "see" your local LOTUS instance, if everything went well, you should be able to add a port of your choice to `docker-compose.yml` and you should be able to access a local version.

```
services:
  lotus-online:
    build: '.'
    restart: always
    image: nponline/lotusweb:latest
    container_name: lotus-online
    volumes:
    - ./data:/data
    ports:
      - '8092:8092' // This is the port you want to add
```
  
And then, after running

```
docker-compose up -d --no-deps --build lotus-online
```

If you run 

```
docker ps -a
```

You should see 

```
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                                 NAMES
c43eaf307982   nponline/lotusweb:latest   "java -Xmx10000m -Dj…"   3 seconds ago    Up 1 second     0.0.0.0:8092->8092/tcp                lotus-online
84f068ba15fe   mongo:4.0.6                "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   27017/tcp, 0.0.0.0:27019->27019/tcp   npoc-mongo-db
```

And opening `0.0.0.0:8092`in your browser should show you your local LOTUS.

Hope this helps and sorry if your question was misunderstood.
